# Generated by Django 4.2.3 on 2024-02-16 14:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huger', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('memebers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
