# Generated by Django 4.2.3 on 2024-03-14 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huger', '0004_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='url',
            field=models.TextField(default=None),
        ),
    ]
