# Generated by Django 4.2.3 on 2024-03-17 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huger', '0005_plan_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='memebers',
        ),
        migrations.AddField(
            model_name='plan',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
